version: '3.8'
networks:
  backend:
    driver: bridge
services:
  backend:
    build: .
    image: backend:latest
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - APP_PORT=${APP_PORT}
    depends_on:
      - db
    ports:
      - ${APP_PORT}:${APP_PORT}
    networks:
      - backend
  db:
    image: postgres:latest
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
    ports:
      - ${DB_PORT}:5432
    networks:
      - backend
